---
- name: Install Jenkins on Debian-based systems
  hosts: control
  gather_facts: false
  become: yes
  tasks:

    - name: Update APT package cache
      apt:
        update_cache: yes      

    - name: Install Java
      apt:
        name: openjdk-11-jdk
        state: present      

    - name: Add Jenkins GPG key
      ansible.builtin.shell: curl -fsSL https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key | sudo tee /usr/share/keyrings/jenkins-keyring.asc > /dev/null

    - name: Add Jenkins repository to sources
      ansible.builtin.lineinfile:
        path: /etc/apt/sources.list.d/jenkins.list
        line: 'deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc] https://pkg.jenkins.io/debian-stable binary/'
        create: yes
        state: present

    - name: Update package manager cache
      ansible.builtin.apt:
        update_cache: yes

    - name: Install Jenkins
      ansible.builtin.apt:
        name: jenkins
        state: present

    - name: Update APT package cache again
      apt:
        update_cache: yes      

    - name: Start Jenkins service
      systemd:
        name: jenkins
        state: started